# fly.toml app configuration file for mail-octo-server
app = "mail-octo-server"
primary_region = "mia"

[build]


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
